package com.demo.poc.commons.core.properties.restclient;

import com.demo.poc.commons.core.tracing.enums.AutoGeneratedParam;
import com.demo.poc.commons.core.tracing.enums.TraceParam;

import java.util.Map;

public interface HeaderTemplate {

  Map<String, String> provided();
  Map<String, String> forwarded();
  Map<String, AutoGeneratedParam> autoGenerated();
  Map<String, TraceParam> tracing();

}
