package com.demo.commons.properties.restclient;

import com.demo.commons.tracing.enums.AutoGeneratedParam;
import com.demo.commons.tracing.enums.TraceParam;

import java.util.Map;

public interface HeaderTemplate {

  Map<String, String> provided();
  Map<String, String> forwarded();
  Map<String, AutoGeneratedParam> autoGenerated();
  Map<String, TraceParam> tracing();

}
